---
title: "Examples"
---

```{r, include=FALSE}
# TODO: should probably bring in the iframe stuff to common
# (but be careful about difference between articles!)
source(
  rprojroot::find_package_root_file("vignettes/_common.R")
)
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

card_gallery <- function(...) {
  layout_column_wrap(
    width = "300px",
    class = "card-gallery",
    ...
  )
}

card_thumb <- function(file, title, subtitle) {
  card(
    card_image(file),
    card_footer(
      card_title(title),
      span(subtitle, class = "text-muted")
    )
  )
}

```

```{css, echo=FALSE}
.plotly {
  .modebar-container {display: none};
}
.section.level2 {
  margin-top: 3rem;
}
.section.level3 {
  margin-top: 2rem;
}
```

Coming soon

## Sidebar layouts

### Multi-page

```{r}
# source("example_gallery/multi_page")
```

### Single-page



### Shared sidebar

###

###
