# ---------------------------------------------------------------
# Grab Bootstrap 3's glyphicons for inclusion as a part of BS3compat
# https://stackoverflow.com/a/33768443/1583084
# ---------------------------------------------------------------

version <- "3.3.5"
zip <- sprintf("https://github.com/twbs/bootstrap-sass/archive/v%s.zip", version)
tmp <- tempfile(fileext = ".zip")
download.file(zip, tmp)
unzip(tmp)

# copy over font files
file.copy(
  Sys.glob("*bootstrap-sass*/assets/fonts/bootstrap/*"),
  "inst/bs3compat/fonts/",
  overwrite = TRUE
)

glyphicons <- readLines(Sys.glob("*bootstrap-sass*/assets/stylesheets/bootstrap/_glyphicons.scss"))
glyphicons <- c(
  "// This file is auto-generated by tools/glyphicons.R",
  "// Consider making edits there before editing this file.",
  "$bootstrap-sass-asset-helper: false;",
  "$icon-font-name: 'glyphicons-halflings-regular';",
  "$icon-font-svg-id: 'glyphicons_halflingsregular';",
  "$icon-font-path: 'fonts/';",
  glyphicons
)

writeLines(glyphicons, "inst/bs3compat/_glyphicons.scss")

unlink("*bootstrap-sass*", recursive = T)
