pkgload::load_all()
gfont_info <- get_gfont_info(update = TRUE)

cat(
  sep = "",
  file = rprojroot::find_package_root_file("R/data_gfont_info.R"),
  "# Generated by ./tools/update_gfont_info.R: do not edit by hand\n",
  "gfont_info <- ", paste0(capture.output({dput(gfont_info)}), collapse = "\n"),
  "\n"
)
